using System;

namespace ElementsLib.Module.Codes
{
    using EnumCode = UInt16;
    public enum ArticleRoleCz : EnumCode
    {
        ARTICLE_UNKNOWN = 0,
        ARTICLE_CONTRACT_TERM,
        ARTICLE_CONTRACT_TIMESHEET,
        ARTICLE_CONTRACT_WORKING,
        ARTICLE_CONTRACT_ABSENCE,
        ARTICLE_CONTRACT_ATTEND_ITEM,
        ARTICLE_POSITION_TERM,
        ARTICLE_POSITION_SCHEDULE,
        ARTICLE_POSITION_TIMESHEET,
        ARTICLE_POSITION_WORKING,
        ARTICLE_POSITION_ABSENCE,
        ARTICLE_POSITION_MONTHLY_AMOUNT = 1000,
        ARTICLE_TAX_DECLARATION,
        ARTICLE_INS_DECLARATION_HEALTH,
        ARTICLE_INS_DECLARATION_SOCIAL,
        ARTICLE_TAX_INCOMES_GENERAL,
        ARTICLE_TAX_INCOMES_HEALTH,
        ARTICLE_TAX_INCOMES_SOCIAL,
        ARTICLE_TAX_INCOMES_ADVANCE,
        ARTICLE_TAX_INCOMES_WITHHOLD_GENERAL,
        ARTICLE_TAX_INCOMES_WITHHOLD_LOLEVEL,
        ARTICLE_TAX_INCOMES_WITHHOLD_TASKAGR,
        ARTICLE_TAX_INCOMES_WITHHOLD_PARTNER,
        ARTICLE_INS_INCOMES_HEALTH,
        ARTICLE_INS_INCOMES_SOCIAL,
        ARTICLE_TAX_BASE_ADVANCE,
        ARTICLE_TAX_BASE_ADVANCE_HEALTH,
        ARTICLE_TAX_BASE_ADVANCE_SOCIAL,
        ARTICLE_TAX_BASE_ADVANCE_PARTIAL,
        ARTICLE_TAX_BASE_ADVANCE_ORDINARY,
        ARTICLE_TAX_BASE_ADVANCE_SOLIDARY,
        ARTICLE_TAX_ADVANCE_ORDINARY,
        ARTICLE_TAX_ADVANCE_SOLIDARY,
        ARTICLE_TAX_ADVANCE_FINAL,
        ARTICLE_TAX_BASE_WITHHOLD,
        ARTICLE_TAX_BASE_WITHHOLD_HEALTH,
        ARTICLE_TAX_BASE_WITHHOLD_SOCIAL,
        ARTICLE_TAX_WITHHOLD_PART,
        ARTICLE_TAX_WITHHOLD_FINAL,
        ARTICLE_TAX_CLAIM_PAYER,
        ARTICLE_TAX_CLAIM_DISABILITY,
        ARTICLE_TAX_CLAIM_STUDYING,
        ARTICLE_TAX_CLAIM_CHILD,
        ARTICLE_TAX_RELIEF_PAYER,
        ARTICLE_TAX_RELIEF_CHILD,
        ARTICLE_TAX_RELIEF_CHILD_BONUS,
        ARTICLE_INS_BASE_HEALTH_COMPOUND,
        ARTICLE_INS_BASE_HEALTH_EMPLOYEE,
        ARTICLE_INS_BASE_HEALTH_EMPLOYER,
        ARTICLE_INS_BASE_SOCIAL_COMPOUND,
        ARTICLE_INS_HEALTH_FINAL,
        ARTICLE_INS_SOCIAL_FINAL,
        ARTICLE_INCOME_GROSS,
        ARTICLE_INCOME_NETTO
    }
    public static class ArticleCzRoleExtensions
    {
        public static string GetSymbol(this ArticleRoleCz article)
        {
            return article.ToString();
        }
    }
}
